name: Continuous Delivery

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ["seafile-caddy", "seafile-server", "seahub", "seahub-media"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Fetch Seafile
        if: ${{ matrix.service == 'seafile-server' || matrix.service == 'seahub' }}
        run: |
          mkdir -p linux/arm/v7
          wget https://github.com/haiwen/seafile-rpi/releases/download/v${{ env.SEAFILE_VERSION }}/seafile-server-${{ env.SEAFILE_VERSION }}-bionic-arm32v7l.tar.gz -O linux/arm/v7/seafile-server_${{ env.SEAFILE_VERSION }}.tar.gz
          mkdir -p linux/arm/v8
          wget https://github.com/haiwen/seafile-rpi/releases/download/v${{ env.SEAFILE_VERSION }}/seafile-server-${{ env.SEAFILE_VERSION }}-bionic-arm64v8l.tar.gz -O linux/arm/v8/seafile-server_${{ env.SEAFILE_VERSION }}.tar.gz
          mkdir -p linux/amd64
          wget https://download.seadrive.org/seafile-server_${{ env.SEAFILE_VERSION }}_x86-64.tar.gz -O linux/amd64/seafile-server_${{ env.SEAFILE_VERSION }}.tar.gz
          cp -r linux seafile-server
          cp -r linux seahub
        env:
          SEAFILE_VERSION: "9.0.2"
      - name: Build the Image
        run: |
          docker build ${{ matrix.service }} \
            --push \
            --no-cache \
            --tag ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm/v8 \
            --label org.opencontainers.image.source="https://github.com/${{ github.repository }}"
        env:
          SEAFILE_VERSION: "9.0.2"
